### ISSUE TITLE
Add scrutinizer.yml

### ISSUE THREAD

**Issue by robertmain** [robertmain/communique#6]
Create scrutinizer yml file thus

``` yml
tools:
    external_code_coverage: true
checks:
    php:
        code_rating: true
        duplication: true
filter:
    paths:
        - src/*
```
